language: python
sudo: true
notifications:
  email: false
python:
    - "3.6"
before_install:
    - sudo add-apt-repository ppa:remik-ziemlinski/nccmp -y --allow-unauthenticated; sudo apt-get update
    - sudo apt-get install nccmp
    - pip install pytest pytest-cov
    - pip install coveralls
    - python setup.py install
script:
    - pytest -v --cov=wrfhydropy
after_success:
    - coveralls